name: "ghav human: Test"
"on":
  push:
    branches:
      - ghav/dev/9427
    paths:
      - .ghav/human
permissions:
  contents: read
env:
  TEST_IMAGE_NODE_MAJOR_VERSION: 22
jobs:
  test-e2e:
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        test_config:
          - file: dockerfile-rpm
            env:
              PACKAGE_MANAGER_TO_TEST: dnf
          - file: dockerfile-rpm
            env:
              PACKAGE_MANAGER_TO_TEST: zypper
          - file: dockerfile-rpm
            env:
              PACKAGE_MANAGER_TO_TEST: yum
          - file: dockerfile-rpm
            env:
              PACKAGE_MANAGER_TO_TEST: rpm
          - file: dockerfile-debian
            env:
              PACKAGE_MANAGER_TO_TEST: apt
          - file: dockerfile-debian
            env:
              PACKAGE_MANAGER_TO_TEST: dpkg
          - file: dockerfile-appimage
            env:
              RUN_APP_IMAGE_TEST: true
    steps:
      - name: Checkout code repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Setup Tests
        uses: ./.github/actions/pretest
        with:
          cache-path: ~/.cache/electron
          cache-key: v-35.7.5-update-electron
      - name: Verify Docs Generation
        run: pnpm generate-all
      - name: e2e Linux Updater tests (install, auto-update, uninstall)
        run: |
          docker build --platform=linux/amd64 -t ${{ matrix.test_config.file }} -f ./test/src/updater/${{ matrix.test_config.file }} .
          TEST_RUNNER_IMAGE_TAG=${{ matrix.test_config.file }} pnpm test-linux
        env:
          TEST_FILES: blackboxUpdateTest,linuxUpdaterTest
          DEBUG: electron-updater,electron-builder
          ADDITIONAL_DOCKER_ARGS: -e PACKAGE_MANAGER_TO_TEST=${{ matrix.test_config.env.PACKAGE_MANAGER_TO_TEST }} -e RUN_APP_IMAGE_TEST=${{ matrix.test_config.env.RUN_APP_IMAGE_TEST || false }}
