name: "ghav before: Test"
"on":
  push:
    branches:
      - ghav/dev/9427
    paths:
      - .ghav/before
permissions:
  contents: read
env:
  TEST_IMAGE_NODE_MAJOR_VERSION: 22
jobs:
  test-e2e:
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        TEST_RUNNER_IMAGE_TAG:
          - dockerfile-rpm
          - dockerfile-debian
          - dockerfile-appimage
    steps:
      - name: Checkout code repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Setup Tests
        uses: ./.github/actions/pretest
        with:
          cache-path: ~/.cache/electron
          cache-key: v-35.7.5-update-electron
      - name: Verify Docs Generation
        run: pnpm generate-all
      - name: e2e Linux Updater tests (install, auto-update, uninstall)
        run: |
          docker build --platform=linux/amd64 -t $TEST_RUNNER_IMAGE_TAG -f ./test/src/updater/$TEST_RUNNER_IMAGE_TAG .
          pnpm test-linux
        env:
          TEST_RUNNER_IMAGE_TAG: ${{ matrix.TEST_RUNNER_IMAGE_TAG }}
          TEST_FILES: blackboxUpdateTest,linuxUpdaterTest
          DEBUG: electron-updater,electron-builder
          ADDITIONAL_DOCKER_ARGS: -e RUN_APP_IMAGE_TEST=true
